Update LocalWebCache.js
with new update of whatsapp web manifest-xxx.json was changed to manifest.json so when you try to upload local saved session you get error like this: 
const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
                                                                                            ^
TypeError: Cannot read properties of null (reading '1')
I suggest some changes to fix this bug)